# Generated by Django 4.2.3 on 2023-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('order', models.CharField(max_length=100, verbose_name='Order')),
                ('payment_method', models.CharField(max_length=100, verbose_name='Payment Method')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Is Paid ?')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount', max_digits=100, verbose_name='Amount')),
                ('currency', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['payment_method'], name='payment_pay_payment_7d17d2_idx')],
            },
        ),
    ]
