version: '3'

services:
  product_service:
    container_name: shop_product_service
    build:
      context: .
      dockerfile: shop_product_service/Dockerfile
    image: shop_product_service
    volumes:
      - .:/shop_product_service
    command: 'python shop_product_service/manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"

  order_service:
    container_name: shop_order_service
    build:
      context: .
      dockerfile: shop_order_service/Dockerfile
    image: shop_order_service
    volumes:
      - .:/shop_order_service
    command: 'python shop_order_service/manage.py runserver 0.0.0.0:8001'
    ports:
      - "8001:8001"

  frontend:
    container_name: shop_frontend
    image: shop_frontend
    build:
      context: .
      dockerfile: shop_frontend/Dockerfile
    ports:
      - "3000:3000" 

