version: '3'

services:
  django:
    container_name: shop_product_service
    build:
      context: .
      dockerfile: shop_product_service/Dockerfile
    image: shop_product_service
    volumes:
      - .:/virtual_shop
    command: 'python shop_product_service/manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"

  frontend:
    container_name: shop_frontend
    image: shop_frontend
    build:
      context: .
      dockerfile: shop_frontend/Dockerfile
    ports:
      - "3000:3000" 

