# Generated by Django 4.2.3 on 2023-08-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_paidinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paidInfo',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
