version: '3'
services:

  product_service:
    container_name: shop_product_service
    build:
      context: .
      dockerfile: Dockerfile
    image: shop_product_service
    volumes:
      - .:/shop_product_service
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"

